In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from rulefit import RuleFit

In [2]:
df = pd.read_csv("../train/train_data_0.csv")
df

,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,...,feature90,feature91,feature92,feature93,feature94,feature95,feature96,feature97,feature98,feature99
0,84.071517,15,95,37,109.222187,41.054423,14,12.635977,14.010126,70,...,26,56,32,30,30,65,36.400093,55,44,11.299354
1,64.376450,12,39,40,108.267721,58.627029,46,80.431019,3.598875,70,...,28,38,69,28,10,44,32.313545,30,45,10.109159
2,61.747596,36,58,7,51.315514,10.865075,53,43.284407,52.822478,70,...,20,45,62,43,29,48,35.294801,27,70,11.926330
3,108.096804,32,73,59,40.416383,12.580249,70,19.908695,59.408556,70,...,26,7,57,68,3,42,37.391035,47,71,10.819648
4,93.659688,14,45,30,85.312636,47.390543,81,30.780931,44.901262,71,...,30,10,46,42,3,42,32.743209,42,47,11.301096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,46.443361,29,59,22,41.987071,57.629751,39,78.792761,4.834577,71,...,26,63,38,66,16,62,36.587602,31,50,7.942675
9996,101.995631,23,57,16,100.037233,41.170912,25,32.059358,31.253103,71,...,29,57,44,52,7,62,37.806850,31,70,11.128170
9997,79.100888,42,36,44,100.913728,59.806790,17,69.167360,47.454068,70,...,22,60,46,4,32,62,32.413842,52,59,10.260244
9998,97.844526,31,41,46,52.108113,51.004928,65,39.811859,36.990671,70,...,25,20,42,4,19,47,36.201993,27,54,8.643205
9999,75.345773,7,31,57,82.398574,46.400732,36,61.709158,2.229820,70,...,28,45,31,53,29,57,36.431810,36,35,7.853727

# exp1 线性生成Label,使用使用EBM Boosting解释

### 线性生成Label

$ y = 5 \times x_0 + 1 \times x_1 + 2 \times x_3$

In [3]:
def normalize(x):
    x_max = x.max()
    x_min = x.min()
    if x.max() == x.min():
        return x
    else:
        result = (x-x_min)/(x_max-x_min)
        return result
df["label"] = df.feature0 *1 + df.feature1 * 1 + df.feature3*1
df["label"] = (normalize(df["label"])>0.5).astype(int)
df

,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,...,feature91,feature92,feature93,feature94,feature95,feature96,feature97,feature98,feature99,label
0,84.071517,15,95,37,109.222187,41.054423,14,12.635977,14.010126,70,...,56,32,30,30,65,36.400093,55,44,11.299354,0
1,64.376450,12,39,40,108.267721,58.627029,46,80.431019,3.598875,70,...,38,69,28,10,44,32.313545,30,45,10.109159,0
2,61.747596,36,58,7,51.315514,10.865075,53,43.284407,52.822478,70,...,45,62,43,29,48,35.294801,27,70,11.926330,0
3,108.096804,32,73,59,40.416383,12.580249,70,19.908695,59.408556,70,...,7,57,68,3,42,37.391035,47,71,10.819648,1
4,93.659688,14,45,30,85.312636,47.390543,81,30.780931,44.901262,71,...,10,46,42,3,42,32.743209,42,47,11.301096,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,46.443361,29,59,22,41.987071,57.629751,39,78.792761,4.834577,71,...,63,38,66,16,62,36.587602,31,50,7.942675,0
9996,101.995631,23,57,16,100.037233,41.170912,25,32.059358,31.253103,71,...,57,44,52,7,62,37.806850,31,70,11.128170,1
9997,79.100888,42,36,44,100.913728,59.806790,17,69.167360,47.454068,70,...,60,46,4,32,62,32.413842,52,59,10.260244,1
9998,97.844526,31,41,46,52.108113,51.004928,65,39.811859,36.990671,70,...,20,42,4,19,47,36.201993,27,54,8.643205,1
9999,75.345773,7,31,57,82.398574,46.400732,36,61.709158,2.229820,70,...,45,31,53,29,57,36.431810,36,35,7.853727,1

In [13]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size = 0.3,random_state = 42)

In [14]:
rf = RuleFit()
X_train = X_train.values()
rf.fit(X_train, y_train, feature_names=df.iloc[:,:-1].columns)

<ipython-input-14-b32e87a9fd23>:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  X_train = X_train.as_matrix()
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 20.850206905972414, tolerance: 0.17499107142857145
  model = cd_fast.enet_coordinate_descent(

RuleFit(max_iter=1000,
        tree_generator=GradientBoostingRegressor(learning_rate=0.01,
                                                 max_depth=100,
                                                 max_leaf_nodes=3,
                                                 n_estimators=555,
                                                 random_state=554,
                                                 subsample=0.08599943084577792))

In [22]:
rules = rf.get_rules()
rules

,rule,type,coef,support,importance
0,feature0,linear,-0.000000,1.000000,0.000000
1,feature1,linear,0.000000,1.000000,0.000000
2,feature2,linear,-0.000036,1.000000,0.000777
3,feature3,linear,-0.000000,1.000000,0.000000
4,feature4,linear,-0.000034,1.000000,0.000799
...,...,...,...,...,...
1849,feature0 <= 49.95111846923828 & feature3 > 24....,rule,-0.000000,0.053245,0.000000
1850,feature0 > 79.70005416870117,rule,-0.000000,0.477537,0.000000
1851,feature0 > 89.00489044189453 & feature13 <= 25...,rule,0.004340,0.084859,0.001209
1852,feature3 <= 23.5 & feature0 > 81.6226425170898...,rule,0.012250,0.071547,0.003157
1853,feature0 <= 83.19965362548828 & feature0 > 62....,rule,-0.000000,0.064892,0.000000

In [25]:
rules = rules[rules.coef != 0].sort_values("importance", ascending=False)
rules

,rule,type,coef,support,importance
1118,feature3 > 12.5 & feature1 > 17.5 & feature0 >...,rule,8.013121e-02,0.347754,3.816308e-02
1169,feature1 > 28.5 & feature3 > 26.5 & feature0 >...,rule,8.954201e-02,0.216306,3.686672e-02
533,feature0 > 71.15070343017578,rule,7.361868e-02,0.584027,3.628584e-02
1180,feature0 > 65.39802169799805 & feature1 > 24.5,rule,7.461087e-02,0.367720,3.597622e-02
1056,feature0 <= 72.1291389465332 & feature3 <= 34....,rule,-1.123310e-01,0.106489,3.464992e-02
...,...,...,...,...,...
294,feature0 > 82.6788444519043,rule,-1.508282e-05,0.394343,7.371112e-06
411,feature78 <= 32.5,rule,-6.751833e-06,0.282862,3.040957e-06
1639,feature53 <= 52.0132999420166,rule,-1.312935e-05,0.044925,2.719610e-06
103,feature42 > 8.059919834136963,rule,5.643300e-06,0.993344,4.588554e-07
886,feature33 > 25.300395011901855,rule,1.248395e-07,0.347754,5.945574e-08